export default {
  ADJ: {
    POS: 'ADJ',
    DESCRIPTION: 'adjective',
    DESCRIPTION_zh: '形容词',
    examples: 'big, old, green, incomprehensible, first',
  },
  ADP: {
    POS: 'ADP',
    DESCRIPTION: 'adposition',
    DESCRIPTION_zh: '介词',
    examples: 'in, to, during',
  },
  ADV: {
    POS: 'ADV',
    DESCRIPTION: 'adverb',
    DESCRIPTION_zh: '副词',
    examples: 'very, tomorrow, down, where, there',
  },
  AUX: {
    POS: 'AUX',
    DESCRIPTION: 'auxiliary',
    DESCRIPTION_zh: '助动词',
    examples: 'is, has (done), will (do), should (do)',
  },
  CONJ: {
    POS: 'CONJ',
    DESCRIPTION: 'conjunction',
    DESCRIPTION_zh: '连词',
    examples: 'and, or, but',
  },
  CCONJ: {
    POS: 'CCONJ',
    DESCRIPTION: 'coordinating conjunction',
    DESCRIPTION_zh: '并列连词',
    examples: 'and, or, but',
  },
  DET: {
    POS: 'DET',
    DESCRIPTION: 'determiner',
    DESCRIPTION_zh: '限定词',
    examples: 'a, an, the',
  },
  INTJ: {
    POS: 'INTJ',
    DESCRIPTION: 'interjection',
    DESCRIPTION_zh: '感叹词',
    examples: 'psst, ouch, bravo, hello',
  },
  NOUN: {
    POS: 'NOUN',
    DESCRIPTION: 'noun',
    DESCRIPTION_zh: '名词',
    examples: 'girl, cat, tree, air, beauty',
  },
  NUM: {
    POS: 'NUM',
    DESCRIPTION: 'numeral',
    DESCRIPTION_zh: '数词',
    examples: '1, 2017, one, seventy-seven, IV, MMXIV',
  },
  PART: {
    POS: 'PART',
    DESCRIPTION: 'particle',
    DESCRIPTION_zh: '助词',
    examples: '’s, not,',
  },
  PRON: {
    POS: 'PRON',
    DESCRIPTION: 'pronoun',
    DESCRIPTION_zh: '代词',
    examples: 'I, you, he, she, myself, themselves, somebody',
  },
  PROPN: {
    POS: 'PROPN',
    DESCRIPTION: 'proper noun',
    DESCRIPTION_zh: '专有名词',
    examples: 'Mary, John, London, NATO, HBO',
  },
  PUNCT: {
    POS: 'PUNCT',
    DESCRIPTION: 'punctuation',
    DESCRIPTION_zh: '标点',
    examples: '., (, ), ?',
  },
  SCONJ: {
    POS: 'SCONJ',
    DESCRIPTION: 'subordinating conjunction',
    DESCRIPTION_zh: '从属连词',
    examples: 'if, while, that',
  },
  SYM: {
    POS: 'SYM',
    DESCRIPTION: 'symbol',
    DESCRIPTION_zh: '符号',
    examples: '$, %, §, ©, +, −, ×, ÷, =, :), 😝',
  },
  VERB: {
    POS: 'VERB',
    DESCRIPTION: 'verb',
    DESCRIPTION_zh: '动词',
    examples: 'run, runs, running, eat, ate, eating',
  },
  X: {
    POS: 'X',
    DESCRIPTION: 'other',
    DESCRIPTION_zh: '其他',
    examples: 'sfpksdpsxmsa',
  },
  SPACE: {
    POS: 'SPACE',
    DESCRIPTION: 'space',
    DESCRIPTION_zh: '空',
  },
};
