export default {
  $: {
    TAG: '$',
    POS: 'SYM',
    MORPHOLOGY: '',
    DESCRIPTION: 'symbol, currency',
    DESCRIPTION_zh: 'symbol, currency',
  },
  '``': {
    TAG: '``',
    POS: 'PUNCT',
    MORPHOLOGY: 'PunctType=quot PunctSide=ini',
    DESCRIPTION: 'opening quotation mark',
    DESCRIPTION_zh: '开引号',
  },
  "''": {
    TAG: "''",
    POS: 'PUNCT',
    MORPHOLOGY: 'PunctType=quot PunctSide=fin',
    DESCRIPTION: 'closing quotation mark',
    DESCRIPTION_zh: '右引号',
  },
  ',': {
    TAG: ',',
    POS: 'PUNCT',
    MORPHOLOGY: 'PunctType=comm',
    DESCRIPTION: 'punctuation mark, comma',
    DESCRIPTION_zh: '标点符号，逗号',
  },
  '-LRB-': {
    TAG: '-LRB-',
    POS: 'PUNCT',
    MORPHOLOGY: 'PunctType=brck PunctSide=ini',
    DESCRIPTION: 'left round bracket',
    DESCRIPTION_zh: '左圆括号',
  },
  '-RRB-': {
    TAG: '-RRB-',
    POS: 'PUNCT',
    MORPHOLOGY: 'PunctType=brck PunctSide=fin',
    DESCRIPTION: 'right round bracket',
    DESCRIPTION_zh: '右圆括号',
  },
  '.': {
    TAG: '.',
    POS: 'PUNCT',
    MORPHOLOGY: 'PunctType=peri',
    DESCRIPTION: 'punctuation mark, sentence closer',
    DESCRIPTION_zh: '标点符号，句子更接近',
  },
  ':': {
    TAG: ':',
    POS: 'PUNCT',
    MORPHOLOGY: '',
    DESCRIPTION: 'punctuation mark, colon or ellipsis',
    DESCRIPTION_zh: '标点符号，冒号或省略号',
  },
  ADD: {
    TAG: 'ADD',
    POS: 'X',
    MORPHOLOGY: '',
    DESCRIPTION: 'email',
    DESCRIPTION_zh: '电子邮件',
  },
  AFX: {
    TAG: 'AFX',
    POS: 'ADJ',
    MORPHOLOGY: 'Hyph=yes',
    DESCRIPTION: 'affix',
    DESCRIPTION_zh: '词缀',
  },
  CC: {
    TAG: 'CC',
    POS: 'CCONJ',
    MORPHOLOGY: 'ConjType=comp',
    DESCRIPTION: 'conjunction, coordinating',
    DESCRIPTION_zh: '结合，协调',
  },
  CD: {
    TAG: 'CD',
    POS: 'NUM',
    MORPHOLOGY: 'NumType=card',
    DESCRIPTION: 'cardinal number',
    DESCRIPTION_zh: '基数',
  },
  DT: {
    TAG: 'DT',
    POS: 'DET',
    MORPHOLOGY: '',
    DESCRIPTION: 'determiner',
    DESCRIPTION_zh: '确定',
  },
  EX: {
    TAG: 'EX',
    POS: 'PRON',
    MORPHOLOGY: 'AdvType=ex',
    DESCRIPTION: 'existential there',
    DESCRIPTION_zh: '存在在那里',
  },
  FW: {
    TAG: 'FW',
    POS: 'X',
    MORPHOLOGY: 'Foreign=yes',
    DESCRIPTION: 'foreign word',
    DESCRIPTION_zh: '外来词',
  },
  GW: {
    TAG: 'GW',
    POS: 'X',
    MORPHOLOGY: '',
    DESCRIPTION: 'additional word in multi-word expression',
    DESCRIPTION_zh: '多词表达中的附加词',
  },
  HYPH: {
    TAG: 'HYPH',
    POS: 'PUNCT',
    MORPHOLOGY: 'PunctType=dash',
    DESCRIPTION: 'punctuation mark, hyphen',
    DESCRIPTION_zh: '标点符号，连字符',
  },
  IN: {
    TAG: 'IN',
    POS: 'ADP',
    MORPHOLOGY: '',
    DESCRIPTION: 'conjunction, subordinating or preposition',
    DESCRIPTION_zh: '连词，从属词或介词',
  },
  JJ: {
    TAG: 'JJ',
    POS: 'ADJ',
    MORPHOLOGY: 'Degree=pos',
    DESCRIPTION: 'adjective',
    DESCRIPTION_zh: '形容词',
  },
  JJR: {
    TAG: 'JJR',
    POS: 'ADJ',
    MORPHOLOGY: 'Degree=comp',
    DESCRIPTION: 'adjective, comparative',
    DESCRIPTION_zh: '形容词，比较',
  },
  JJS: {
    TAG: 'JJS',
    POS: 'ADJ',
    MORPHOLOGY: 'Degree=sup',
    DESCRIPTION: 'adjective, superlative',
    DESCRIPTION_zh: '形容词，最高级',
  },
  LS: {
    TAG: 'LS',
    POS: 'X',
    MORPHOLOGY: 'NumType=ord',
    DESCRIPTION: 'list item marker',
    DESCRIPTION_zh: '清单项目标记',
  },
  MD: {
    TAG: 'MD',
    POS: 'VERB',
    MORPHOLOGY: 'VerbType=mod',
    DESCRIPTION: 'verb, modal auxiliary',
    DESCRIPTION_zh: '动词，情态辅助',
  },
  NFP: {
    TAG: 'NFP',
    POS: 'PUNCT',
    MORPHOLOGY: '',
    DESCRIPTION: 'superfluous punctuation',
    DESCRIPTION_zh: '多余的标点',
  },
  NIL: {
    TAG: 'NIL',
    POS: 'X',
    MORPHOLOGY: '',
    DESCRIPTION: 'missing tag',
    DESCRIPTION_zh: '缺少标签',
  },
  NN: {
    TAG: 'NN',
    POS: 'NOUN',
    MORPHOLOGY: 'Number=sing',
    DESCRIPTION: 'noun, singular or mass',
    DESCRIPTION_zh: '名词，单数或质量',
  },
  NNP: {
    TAG: 'NNP',
    POS: 'PROPN',
    MORPHOLOGY: 'NounType=prop Number=sing',
    DESCRIPTION: 'noun, proper singular',
    DESCRIPTION_zh: '名词，专有单数',
  },
  NNPS: {
    TAG: 'NNPS',
    POS: 'PROPN',
    MORPHOLOGY: 'NounType=prop Number=plur',
    DESCRIPTION: 'noun, proper plural',
    DESCRIPTION_zh: '名词，专有复数',
  },
  NNS: {
    TAG: 'NNS',
    POS: 'NOUN',
    MORPHOLOGY: 'Number=plur',
    DESCRIPTION: 'noun, plural',
    DESCRIPTION_zh: '名词，复数',
  },
  PDT: {
    TAG: 'PDT',
    POS: 'DET',
    MORPHOLOGY: '',
    DESCRIPTION: 'predeterminer',
    DESCRIPTION_zh: '预定者',
  },
  POS: {
    TAG: 'POS',
    POS: 'PART',
    MORPHOLOGY: 'Poss=yes',
    DESCRIPTION: 'possessive ending',
    DESCRIPTION_zh: '所有格结局',
  },
  PRP: {
    TAG: 'PRP',
    POS: 'PRON',
    MORPHOLOGY: 'PronType=prs',
    DESCRIPTION: 'pronoun, personal',
    DESCRIPTION_zh: '人称代词',
  },
  PRP$: {
    TAG: 'PRP$',
    POS: 'DET',
    MORPHOLOGY: 'PronType=prs Poss=yes',
    DESCRIPTION: 'pronoun, possessive',
    DESCRIPTION_zh: '代词，所有格',
  },
  RB: {
    TAG: 'RB',
    POS: 'ADV',
    MORPHOLOGY: 'Degree=pos',
    DESCRIPTION: 'adverb',
    DESCRIPTION_zh: '副词',
  },
  RBR: {
    TAG: 'RBR',
    POS: 'ADV',
    MORPHOLOGY: 'Degree=comp',
    DESCRIPTION: 'adverb, comparative',
    DESCRIPTION_zh: '副词，比较',
  },
  RBS: {
    TAG: 'RBS',
    POS: 'ADV',
    MORPHOLOGY: 'Degree=sup',
    DESCRIPTION: 'adverb, superlative',
    DESCRIPTION_zh: '副词，最高级',
  },
  RP: {
    TAG: 'RP',
    POS: 'ADP',
    MORPHOLOGY: '',
    DESCRIPTION: 'adverb, particle',
    DESCRIPTION_zh: '副词，粒子',
  },
  SP: {
    TAG: 'SP',
    POS: 'SPACE',
    MORPHOLOGY: '',
    DESCRIPTION: 'space',
    DESCRIPTION_zh: '空间',
  },
  SYM: {
    TAG: 'SYM',
    POS: 'SYM',
    MORPHOLOGY: '',
    DESCRIPTION: 'symbol',
    DESCRIPTION_zh: '符号',
  },
  TO: {
    TAG: 'TO',
    POS: 'PART',
    MORPHOLOGY: 'PartType=inf VerbForm=inf',
    DESCRIPTION: 'infinitival “to”',
    DESCRIPTION_zh: '不定式的 “to”',
  },
  UH: {
    TAG: 'UH',
    POS: 'INTJ',
    MORPHOLOGY: '',
    DESCRIPTION: 'interjection',
    DESCRIPTION_zh: '欹',
  },
  VB: {
    TAG: 'VB',
    POS: 'VERB',
    MORPHOLOGY: 'VerbForm=inf',
    DESCRIPTION: 'verb, base form',
    DESCRIPTION_zh: '动词，基本形式',
  },
  VBD: {
    TAG: 'VBD',
    POS: 'VERB',
    MORPHOLOGY: 'VerbForm=fin Tense=past',
    DESCRIPTION: 'verb, past tense',
    DESCRIPTION_zh: '动词，过去式',
  },
  VBG: {
    TAG: 'VBG',
    POS: 'VERB',
    MORPHOLOGY: 'VerbForm=part Tense=pres Aspect=prog',
    DESCRIPTION: 'verb, gerund or present participle',
    DESCRIPTION_zh: '动词，动名词或现在分词',
  },
  VBN: {
    TAG: 'VBN',
    POS: 'VERB',
    MORPHOLOGY: 'VerbForm=part Tense=past Aspect=perf',
    DESCRIPTION: 'verb, past participle',
    DESCRIPTION_zh: '动词，过去分词',
  },
  VBP: {
    TAG: 'VBP',
    POS: 'VERB',
    MORPHOLOGY: 'VerbForm=fin Tense=pres',
    DESCRIPTION: 'verb, non-3rd person singular present',
    DESCRIPTION_zh: '动词，非第三人称单数',
  },
  VBZ: {
    TAG: 'VBZ',
    POS: 'VERB',
    MORPHOLOGY: 'VerbForm=fin Tense=pres Number=sing Person=three',
    DESCRIPTION: 'verb, 3rd person singular present',
    DESCRIPTION_zh: '动词，第三人称单数',
  },
  WDT: {
    TAG: 'WDT',
    POS: 'DET',
    MORPHOLOGY: '',
    DESCRIPTION: 'wh-determiner',
    DESCRIPTION_zh: '决定因素',
  },
  WP: {
    TAG: 'WP',
    POS: 'PRON',
    MORPHOLOGY: '',
    DESCRIPTION: 'wh-pronoun, personal',
    DESCRIPTION_zh: '个人代名词',
  },
  WP$: {
    TAG: 'WP$',
    POS: 'DET',
    MORPHOLOGY: 'Poss=yes',
    DESCRIPTION: 'wh-pronoun, possessive',
    DESCRIPTION_zh: 'Wh代词，所有格',
  },
  WRB: {
    TAG: 'WRB',
    POS: 'ADV',
    MORPHOLOGY: '',
    DESCRIPTION: 'wh-adverb',
    DESCRIPTION_zh: '副词',
  },
  XX: {
    TAG: 'XX',
    POS: 'X',
    MORPHOLOGY: '',
    DESCRIPTION: 'unknown',
    DESCRIPTION_zh: '未知',
  },
  _SP: {
    TAG: '_SP',
    POS: 'SPACE',
    MORPHOLOGY: '',
    DESCRIPTION: '',
    DESCRIPTION_zh: '',
  },
};
